# Generated by Django 3.0.1 on 2020-01-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, '未通过'), (2, '申请中'), (3, '尚未排课'), (4, '已排课')], default=2)),
                ('cname', models.CharField(max_length=128)),
                ('credit', models.CharField(max_length=128)),
                ('is_compulsory', models.CharField(choices=[('COMPULSORY', '必修'), ('UNCOMPULSORY', '选修'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=128)),
                ('cdepart', models.CharField(max_length=128)),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name': '开课表',
                'verbose_name_plural': '开课表',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.CharField(max_length=128)),
                ('floor', models.CharField(max_length=64)),
                ('room_id', models.CharField(max_length=64)),
                ('capacity', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '教室',
                'verbose_name_plural': '教室',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=128)),
                ('tdepart', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('tmid', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')])),
                ('period', models.IntegerField(choices=[(1, '8:00-9:30'), (2, '10:00-11:30'), (3, '12:00-13:30'), (4, '14:00-15:30'), (5, '16:00-17:30'), (6, '18:00-19:30'), (7, '19:40-21:10'), (8, '8:00-10:30'), (9, '14:00-16:30'), (10, '18:00-21:00')])),
            ],
            options={
                'verbose_name': '时间',
                'verbose_name_plural': '时间',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('identity', models.CharField(choices=[('administrator', '教务处'), ('teacher', '教师'), ('student', '学生')], default='student', max_length=64)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS_app.Apply')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CS_app.Room')),
                ('time1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1', to='CS_app.Time')),
                ('time2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='CS_app.Time')),
            ],
            options={
                'verbose_name': '排课',
                'verbose_name_plural': '排课',
            },
        ),
        migrations.AddField(
            model_name='apply',
            name='tid1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at1', to='CS_app.Teacher'),
        ),
        migrations.AddField(
            model_name='apply',
            name='tid2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='at2', to='CS_app.Teacher'),
        ),
    ]
